### ISSUE TITLE
throw when a promise isn't returned?

### ISSUE THREAD

**Issue by matthewmueller** [blakeembrey/throwback#1]
not sure how you feel about this (or what would need to change), but it's pretty easy to forget to return next in:

``` js
function (ctx, next) {
   return next().then(v => { ... })
}
```

what do you think about throwing if `undefined` is returned? 

unfortunately, right now not returning a promise silently causes the control flow to change.

**Comment by blakeembrey** [comment]
Sounds great. I can't see any real caveats to enabling this 👍

The code change required would be: https://github.com/blakeembrey/throwback/blob/master/src/index.ts#L38-L43. Something like `const res = fn(); if (res === undefined) { throw }; return resolve(res)`.

**Comment by blakeembrey** [comment]
The only unfortunate thing is that it doesn't help once you switch to `async`/`await` (which would always return a promise) or your middleware legitimately returns `undefined` (but we can warn in the README to wrap it in a promise).

**Comment by blakeembrey** [comment]
Added with a "debug mode" in https://github.com/serviejs/throwback/commit/12d80cfceb1c82cedb1eff638f3af38dc7c75169 to use a slower code path in development. The next release is a pretty big code change but should make things simpler, easier and faster to work with (especially `next(ctx)` support for things like HTTP request retry support in `popsicle`).
